# Generated by Django 5.0.7 on 2024-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(help_text='Link type', max_length=128)),
                ('url', models.URLField(help_text='Link URL', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'links',
            },
        ),
    ]
