# Generated by Django 5.0.7 on 2024-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0002_alter_signalset_severity_pyramid_rungs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='data_source',
            field=models.CharField(blank=True, max_length=128, verbose_name='Data Source'),
        ),
    ]
