# Generated by Django 5.0.7 on 2024-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0004_alter_signalset_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='origin_datasource',
            field=models.TextField(blank=True, verbose_name='Origin Data Source'),
        ),
    ]
