# Generated by Django 5.0.7 on 2024-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0005_alter_signalset_origin_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='missingness',
            field=models.TextField(blank=True, help_text='Missingness of the signal set.', verbose_name='missingness'),
        ),
    ]
