# Generated by Django 5.0.7 on 2024-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0006_alter_signalset_missingness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='dua_required',
            field=models.CharField(help_text='Whether a data use agreement is required to access the signal set.', max_length=128, verbose_name='DUA Required'),
        ),
    ]
