# Generated by Django 5.0.7 on 2024-10-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0007_alter_signalset_dua_required'),
        ('signals', '0002_auto_20241002_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='available_geography',
            field=models.ManyToManyField(blank=True, related_name='signal_sets', through='signal_sets.SignalSetGeography', to='signals.geography', verbose_name='Available Geography'),
        ),
        migrations.AlterField(
            model_name='signalset',
            name='geographic_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signal_sets', to='signals.geographicscope', verbose_name='Geographic Scope'),
        ),
        migrations.AlterField(
            model_name='signalset',
            name='pathogens',
            field=models.ManyToManyField(blank=True, help_text='Pathogen(s) associated with the signal set.', related_name='signal_sets', to='signals.pathogen', verbose_name='Pathogen'),
        ),
    ]
