# Generated by Django 5.0.7 on 2024-10-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0008_alter_signalset_available_geography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='censoring',
            field=models.CharField(blank=True, help_text='Data censoring of the signal set.', max_length=255, null=True, verbose_name='data censoring'),
        ),
        migrations.AlterField(
            model_name='signalset',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
