# Generated by Django 5.0.7 on 2024-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0009_alter_signalset_censoring_alter_signalset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalset',
            old_name='available_geography',
            new_name='available_geographies',
        ),
        migrations.AddField(
            model_name='signalset',
            name='geographic_granulalarity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Geographic Granularity'),
        ),
    ]
