# Generated by Django 5.0.7 on 2024-10-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_alter_datasource_display_name'),
        ('signal_sets', '0011_rename_geographic_granulalarity_signalset_geographic_granularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalset',
            name='data_source',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='signal_sets', to='datasources.datasource', verbose_name='Data Source'),
        ),
    ]
