# Generated by Django 5.0.7 on 2024-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0012_alter_signalset_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalset',
            name='data_description',
        ),
        migrations.RemoveField(
            model_name='signalset',
            name='link_to_dictionary',
        ),
        migrations.AddField(
            model_name='signalset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Signal Set description'),
        ),
        migrations.AddField(
            model_name='signalset',
            name='link_to_documentation',
            field=models.CharField(blank=True, help_text='Link to documentation.', max_length=255, null=True, verbose_name='Link to documentation'),
        ),
        migrations.AlterField(
            model_name='signalset',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Signal Set name'),
        ),
    ]
