# Generated by Django 5.0.7 on 2024-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0013_remove_signalset_data_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalset',
            name='endpoint',
            field=models.CharField(blank=True, help_text='Endpoint of the signal set.', max_length=255, null=True, verbose_name='endpoint'),
        ),
    ]
