# Generated by Django 5.0.7 on 2024-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_sets', '0014_signalset_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalset',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Signal Set short name'),
        ),
    ]
