# Generated by Django 5.0.7 on 2024-10-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW signals_signal_view AS (
                SELECT
                ss.id,
                ss.name as "name",
                ss.display_name AS "display_name",
                ss.active AS "active",
                ds.display_name AS "datasource",
                ss.description AS "description",
                sg.name AS "geographic_scope",
                ss.temporal_scope_start AS "temporal_scope_start",
                ss.temporal_scope_end AS "temporal_scope_end",
                ss.time_type AS "time_type",
                GROUP_CONCAT(DISTINCT CONCAT(signal_geo.name, '', IF(ss2.aggregated_by_delphi, '(by Delphi)', ''))) AS "available_geography", 
                GROUP_CONCAT(DISTINCT sp.name) AS "pathogens",
                ss.reporting_cadence AS "reporting_cadence",
                ss.typical_reporting_lag AS "typical_reporting_lag",
                ss.typical_revision_cadence AS "typical_revision_cadence",
                ss.demographic_scope AS "demographic_scope",
                ss3.display_name AS "severity_pyramid_rung",
                ss.missingness AS "missingness",
                ss.license AS "license",
                ss.restrictions AS "restrictions",
                ss.from_date AS "from_date",
                ss.to_date AS "to_date",
                ss.signal_availability_days AS "signal_availability_days"
            FROM signals_signal ss
            LEFT JOIN datasources_sourcesubdivision ds
            ON ss.source_id = ds.id
            LEFT JOIN signals_geographicscope sg
            ON ss.geographic_scope_id = sg.id
            LEFT JOIN signals_signal_pathogen ssp
            ON ss.id = ssp.signal_id
            LEFT JOIN signals_severitypyramidrung ss3
            ON ss.severity_pyramid_rung_id = ss3.id
            LEFT JOIN signals_signalgeography ss2
            ON ss.id = ss2.signal_id
            LEFT JOIN signals_geography signal_geo
            ON signal_geo.id = ss2.geography_id
            LEFT JOIN signals_pathogen sp
            ON sp.id = ssp.pathogen_id
            GROUP BY
                ss.id,
                ss.display_name,
                ss.active,
                ds.display_name,
                ss.description,
                sg.name,
                ss.temporal_scope_start,
                ss.temporal_scope_end,
                ss.time_type,
                ss.reporting_cadence,
                ss.typical_reporting_lag,
                ss.typical_revision_cadence,
                ss.demographic_scope,
                ss3.display_name,
                ss.missingness,
                ss.license,
                ss.restrictions
            )
            """
        )
    ]
