# Generated by Django 5.0.7 on 2024-11-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('datasources', '0002_alter_datasource_display_name'),
        ('signals', '0003_signal_signal_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='active',
            field=models.BooleanField(blank=True, default=False, help_text='Ongoing', null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='available_geography',
            field=models.ManyToManyField(blank=True, help_text='Available geographies for the signal.', null=True, related_name='signals', through='signals.SignalGeography', to='signals.geography'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='demographic_scope',
            field=models.CharField(blank=True, help_text='Demographic scope of the signal.', max_length=255, null=True, verbose_name='demographic scope'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the signal.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name of the signal.', max_length=255, null=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='geographic_scope',
            field=models.ForeignKey(blank=True, help_text='Geographic scope of the signal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='signals.geographicscope'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='has_sample_size',
            field=models.BooleanField(blank=True, default=False, help_text='Has sample size', null=True, verbose_name='has sample size'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='has_stderr',
            field=models.BooleanField(blank=True, default=False, help_text='Has stderr', null=True, verbose_name='has stderr'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='high_values_are',
            field=models.CharField(blank=True, help_text='High values are', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_cumulative',
            field=models.BooleanField(blank=True, default=False, help_text='Is cumulative', null=True, verbose_name='is cumulative'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_smoothed',
            field=models.BooleanField(blank=True, default=False, help_text='Is smoothed', null=True, verbose_name='is smoothed'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='is_weighted',
            field=models.BooleanField(blank=True, default=False, help_text='Is weighted', null=True, verbose_name='is weighted'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='organization_access_list',
            field=models.CharField(blank=True, help_text='Organisations Access List. Who may access this signal?', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='organization_sharing_list',
            field=models.CharField(blank=True, help_text='Organisations Sharing List. Who may share this signal?', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pathogen',
            field=models.ManyToManyField(blank=True, help_text='Pathogen/Disease area', null=True, related_name='signals', to='signals.pathogen'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='related_links',
            field=models.ManyToManyField(blank=True, help_text='Related signal links.', null=True, related_name='signals', to='base.link'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='reporting_cadence',
            field=models.CharField(blank=True, help_text='Reporting cadence of the signal.', max_length=255, null=True, verbose_name='reporting cadence'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Source Subdivision', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='datasources.sourcesubdivision'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_end',
            field=models.CharField(blank=True, help_text='Temporal scope end of the signal.', max_length=255, null=True, verbose_name='temporal scope end'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_end_note',
            field=models.TextField(blank=True, help_text='Temporal scope end note of the signal.', null=True, verbose_name='temporal scope end note'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_start',
            field=models.CharField(blank=True, help_text='Temporal scope start of the signal.', max_length=255, null=True, verbose_name='temporal scope start'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_start_note',
            field=models.TextField(blank=True, help_text='Temporal scope start note of the signal.', null=True, verbose_name='temporal scope start note'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='time_label',
            field=models.CharField(blank=True, help_text='Time label of the signal.', max_length=255, null=True, verbose_name='time label'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='time_type',
            field=models.CharField(blank=True, help_text='Time type of the signal.', max_length=255, null=True, verbose_name='time type'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='typical_reporting_lag',
            field=models.CharField(blank=True, help_text='Typical reporting lag of the signal.', max_length=255, null=True, verbose_name='typical reporting lag'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='typical_revision_cadence',
            field=models.TextField(blank=True, help_text='Typical revision cadence of the signal.', null=True, verbose_name='typical revision cadence'),
        ),
    ]
