# Generated by Django 5.0.7 on 2024-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('signals', '0004_alter_signal_active_alter_signal_available_geography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='available_geography',
            field=models.ManyToManyField(blank=True, help_text='Available geographies for the signal.', related_name='signals', through='signals.SignalGeography', to='signals.geography'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pathogen',
            field=models.ManyToManyField(blank=True, help_text='Pathogen/Disease area', related_name='signals', to='signals.pathogen'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='related_links',
            field=models.ManyToManyField(blank=True, help_text='Related signal links.', related_name='signals', to='base.link'),
        ),
    ]
