# Generated by Django 5.0.7 on 2024-11-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_signal_available_geography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the signal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='signals.category'),
        ),
    ]
