# Generated by Django 5.0.7 on 2024-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_alter_signal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='member_description',
            field=models.TextField(blank=True, help_text='Member description of the signal.', null=True, verbose_name='member description'),
        ),
        migrations.AddField(
            model_name='signal',
            name='member_name',
            field=models.CharField(blank=True, help_text='Member name of the signal.', max_length=255, null=True, verbose_name='member name'),
        ),
    ]
