# Generated by Django 5.0.7 on 2024-12-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_signal_member_description_signal_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='member_short_name',
            field=models.CharField(blank=True, help_text='Member short name of the signal.', max_length=255, null=True, verbose_name='member short name'),
        ),
    ]
