# Generated by Django 5.0.7 on 2025-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_signal_member_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathogen',
            options={'verbose_name_plural': 'Pathogens'},
        ),
        migrations.AddField(
            model_name='pathogen',
            name='used_in',
            field=models.CharField(choices=[('signals', 'Signals'), ('signal_sets', 'Signal Sets')], default='signals', max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='pathogen',
            unique_together={('name', 'used_in')},
        ),
    ]
