# Generated by Django 5.0.7 on 2025-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_alter_pathogen_options_pathogen_used_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogen',
            name='name',
            field=models.CharField(help_text='Name of the pathogen.', max_length=128, verbose_name='name'),
        ),
    ]
