# Generated by Django 5.0.7 on 2025-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_alter_pathogen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicscope',
            name='used_in',
            field=models.CharField(choices=[('signals', 'Signals'), ('signal_sets', 'Signal Sets')], default='signals', max_length=11),
        ),
    ]
