# Generated by Django 5.0.7 on 2025-01-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_alter_geographicscope_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicscope',
            options={'verbose_name_plural': 'Geographic Scopes'},
        ),
        migrations.AlterUniqueTogether(
            name='geographicscope',
            unique_together={('name', 'used_in')},
        ),
    ]
