# Generated by Django 5.0.7 on 2025-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_alter_geographicscope_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='used_in',
            field=models.CharField(choices=[('signals', 'Signals'), ('signal_sets', 'Signal Sets')], default='signals', max_length=11),
        ),
        migrations.AlterField(
            model_name='geography',
            name='name',
            field=models.CharField(help_text='Name of the geography.', max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='geography',
            unique_together={('name', 'used_in')},
        ),
    ]
