# Generated by Django 5.0.7 on 2025-01-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_geography_used_in_alter_geography_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='severitypyramidrung',
            name='used_in',
            field=models.CharField(choices=[('signals', 'Signals'), ('signal_sets', 'Signal Sets')], default='signals', max_length=11),
        ),
        migrations.AlterField(
            model_name='severitypyramidrung',
            name='name',
            field=models.CharField(help_text='Name of the severity pyramid rung.', max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='severitypyramidrung',
            unique_together={('name', 'used_in')},
        ),
    ]
