# Generated by Django 5.0.7 on 2025-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_signal_source_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='severitypyramidrung',
            name='display_order_number',
            field=models.IntegerField(help_text='Display order number of the severity pyramid rung.', null=True, verbose_name='display order number'),
        ),
    ]
