# Generated by Django 5.0.7 on 2025-01-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_signal_source_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSourceDbView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('signal', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ("signal_set", models.BigIntegerField(serialize=False)),
            ],
            options={
                'db_table': 'signals_signal_source_view',
                'managed': False,
            },
        ),
    ]
