# Generated by Django 5.0.7 on 2025-03-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0017_severitypyramidrung_display_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEndointSignal',
            fields=[
            ],
            options={
                'verbose_name': 'Other Endpoint Signal',
                'verbose_name_plural': 'Other Endpoint Signals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('signals.signal',),
        ),
    ]
