# Generated by Django 5.0.7 on 2024-10-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('license', models.CharField(blank=True, max_length=128, verbose_name='License')),
                ('related_links', models.ManyToManyField(blank=True, related_name='data_sources', to='base.link', verbose_name='Related Links')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_subdivisions', to='datasources.datasource', verbose_name='Data Source')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
